cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel2045_5_sub/Subsystem/Mysubsystem_17','user1');
hilite_system('sampleModel2045_5_sub/Subsystem/Mysubsystem_17/cfblk29','user1');
hilite_system('sampleModel2045_5_sub/Subsystem/Mysubsystem_17/cfblk5','user1');
hilite_system('sampleModel2045_5_sub/Subsystem/Mysubsystem_7','user1');
hilite_system('sampleModel2045_5_sub/Subsystem/Mysubsystem_7/cfblk121','user1');
hilite_system('sampleModel2045_5_sub/Subsystem/Mysubsystem_7/cfblk75','user1');
