cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1944_sub/Subsystem/cfblk114','user1');
hilite_system('sampleModel1944_sub/Subsystem/cfblk20','user1');
hilite_system('sampleModel1944_sub/Subsystem/cfblk24','user1');
hilite_system('sampleModel1944_sub/Subsystem/cfblk26','user1');
hilite_system('sampleModel1944_sub/Subsystem/cfblk31','user1');
hilite_system('sampleModel1944_sub/Subsystem/cfblk50','user1');
hilite_system('sampleModel1944_sub/Subsystem/cfblk56','user1');
hilite_system('sampleModel1944_sub/Subsystem/cfblk58','user1');
hilite_system('sampleModel1944_sub/Subsystem/cfblk59','user1');
hilite_system('sampleModel1944_sub/Subsystem/cfblk63','user1');
hilite_system('sampleModel1944_sub/Subsystem/cfblk65','user1');
hilite_system('sampleModel1944_sub/Subsystem/cfblk72','user1');
hilite_system('sampleModel1944_sub/Subsystem/cfblk8','user1');
hilite_system('sampleModel1944_sub/Subsystem/cfblk92','user1');
