// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1810\sampleModel1810_5_sub\Mysubsystem_33.v
// Created: 2024-08-14 12:16:43
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_33
// Source Path: sampleModel1810_5_sub/Subsystem/Mysubsystem_33
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_33
          (clk,
           reset,
           enb,
           Out1,
           Out2);


  input   clk;
  input   reset;
  input   enb;
  output  [7:0] Out1;  // uint8
  output  [7:0] Out2;  // uint8


  wire [15:0] cfblk132_out1;  // uint16
  wire [7:0] cfblk161_out1;  // uint8


  cfblk132 u_cfblk132 (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .y(cfblk132_out1)  // uint16
                       );

  assign cfblk161_out1 = cfblk132_out1[7:0];



  assign Out1 = cfblk161_out1;

  assign Out2 = cfblk161_out1;

endmodule  // Mysubsystem_33

