vlib work
vlog  Mysubsystem_36.v
vlog  cfblk1.v
vlog  cfblk127.v
vlog  cfblk2.v
vlog  cfblk4.v
vlog  DotProduct.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  Subsystem.v
