cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1995_sub_sub/Subsystem/Subsystem/cfblk103','user1');
hilite_system('sampleModel1995_sub_sub/Subsystem/Subsystem/cfblk122','user1');
hilite_system('sampleModel1995_sub_sub/Subsystem/Subsystem/cfblk125','user1');
hilite_system('sampleModel1995_sub_sub/Subsystem/Subsystem/cfblk130','user1');
hilite_system('sampleModel1995_sub_sub/Subsystem/Subsystem/cfblk155','user1');
hilite_system('sampleModel1995_sub_sub/Subsystem/Subsystem/cfblk169','user1');
hilite_system('sampleModel1995_sub_sub/Subsystem/Subsystem/cfblk206','user1');
hilite_system('sampleModel1995_sub_sub/Subsystem/Subsystem/cfblk207','user1');
hilite_system('sampleModel1995_sub_sub/Subsystem/Subsystem/cfblk208','user1');
hilite_system('sampleModel1995_sub_sub/Subsystem/Subsystem/cfblk46','user1');
hilite_system('sampleModel1995_sub_sub/Subsystem/Subsystem/cfblk73','user1');
hilite_system('sampleModel1995_sub_sub/Subsystem/Subsystem/cfblk85','user1');
hilite_system('sampleModel1995_sub_sub/Subsystem/Subsystem/cfblk98','user1');
