cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel2052_sub/Subsystem/cfblk114','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk135','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk182','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk183','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk2','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk2/Nonpositive','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk24','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk26','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk39','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk42','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk53','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk63','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk65','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk69','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk71','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk8','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk8/Delay Input1','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk8/FixPt Relational Operator','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk88','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk9','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk9/Delay Input1','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk9/FixPt Relational Operator','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk9/Negative','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk90','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk9/Negative/Compare','user1');
hilite_system('sampleModel2052_sub/Subsystem/cfblk9/Negative/Constant','user1');
