// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1427\sampleModel1427_3_sub\Mysubsystem_25.v
// Created: 2024-08-12 04:07:26
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_25
// Source Path: sampleModel1427_3_sub/Subsystem/Mysubsystem_25
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_25
          (In1,
           y);


  input   [7:0] In1;  // uint8
  output  [7:0] y;  // uint8


  wire [7:0] cfblk59_const_val_1;  // uint8
  wire [7:0] cfblk59_out1;  // uint8
  wire [7:0] cfblk5_out1;  // uint8


  assign cfblk59_const_val_1 = 8'b00000000;



  assign cfblk59_out1 = In1 + cfblk59_const_val_1;



  assign cfblk5_out1 = cfblk59_out1 & 8'b11111110;



  assign y = cfblk5_out1;

endmodule  // Mysubsystem_25

