vlib work
vlog  cfblk140.v
vlog  cfblk141.v
vlog  cfblk142.v
vlog  cfblk143.v
vlog  cfblk144.v
vlog  DotProduct.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  DotProduct_block3.v
vlog  DotProduct_block4.v
vlog  DotProduct_block5.v
vlog  DotProduct_block6.v
vlog  DotProduct_block7.v
vlog  DotProduct_block8.v
vlog  DotProduct_block9.v
vlog  DotProduct_block10.v
vlog  DotProduct_block11.v
vlog  DotProduct_block12.v
vlog  Subsystem.v
vlog  Subsystem_tb.v
