cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1847_sub_sub/Subsystem/Subsystem/cfblk111','user1');
hilite_system('sampleModel1847_sub_sub/Subsystem/Subsystem/cfblk118','user1');
hilite_system('sampleModel1847_sub_sub/Subsystem/Subsystem/cfblk187','user1');
hilite_system('sampleModel1847_sub_sub/Subsystem/Subsystem/cfblk189','user1');
hilite_system('sampleModel1847_sub_sub/Subsystem/Subsystem/cfblk2','user1');
hilite_system('sampleModel1847_sub_sub/Subsystem/Subsystem/cfblk21','user1');
hilite_system('sampleModel1847_sub_sub/Subsystem/Subsystem/cfblk23','user1');
hilite_system('sampleModel1847_sub_sub/Subsystem/Subsystem/cfblk33','user1');
hilite_system('sampleModel1847_sub_sub/Subsystem/Subsystem/cfblk44','user1');
hilite_system('sampleModel1847_sub_sub/Subsystem/Subsystem/cfblk46','user1');
hilite_system('sampleModel1847_sub_sub/Subsystem/Subsystem/cfblk54','user1');
hilite_system('sampleModel1847_sub_sub/Subsystem/Subsystem/cfblk55','user1');
hilite_system('sampleModel1847_sub_sub/Subsystem/Subsystem/cfblk61','user1');
hilite_system('sampleModel1847_sub_sub/Subsystem/Subsystem/cfblk69','user1');
hilite_system('sampleModel1847_sub_sub/Subsystem/Subsystem/cfblk90','user1');
hilite_system('sampleModel1847_sub_sub/Subsystem/Subsystem/cfblk97','user1');
