// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1402\sampleModel1402_2_sub\Mysubsystem_1.v
// Created: 2024-06-10 01:55:30
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_1
// Source Path: sampleModel1402_2_sub/Subsystem/Mysubsystem_1
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_1
          (clk,
           reset,
           enb,
           Out1,
           y,
           y1,
           Out4);


  input   clk;
  input   reset;
  input   enb;
  output  [7:0] Out1;  // uint8
  output  [7:0] y;  // uint8
  output  [7:0] y1;  // uint8
  output  [7:0] Out4;  // uint8


  wire [7:0] cfblk133_out1;  // uint8
  wire [7:0] cfblk135_out1;  // uint8
  wire [7:0] cfblk131_out1;  // uint8
  wire [7:0] cfblk88_out1;  // uint8


  cfblk133 u_cfblk133 (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .y(cfblk133_out1)  // uint8
                       );

  assign Out1 = cfblk133_out1;

  cfblk135 u_cfblk135 (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .y(cfblk135_out1)  // uint8
                       );

  assign y = cfblk135_out1;

  cfblk131 u_cfblk131 (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .y(cfblk131_out1)  // uint8
                       );

  assign y1 = cfblk131_out1;

  assign cfblk88_out1 = cfblk135_out1 + cfblk133_out1;



  assign Out4 = cfblk88_out1;

endmodule  // Mysubsystem_1

