// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1510\sampleModel1510_5_sub\Mysubsystem_28.v
// Created: 2024-07-01 04:16:22
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_28
// Source Path: sampleModel1510_5_sub/Subsystem/Mysubsystem_28
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_28
          (In1,
           In2,
           Out1);


  input   [7:0] In1;  // uint8
  input   [7:0] In2;  // uint8
  output  [7:0] Out1;  // uint8


  wire cfblk181_out1_is_not0;
  wire cfblk182_out1_is_not0;
  wire cfblk5_out1;
  wire [7:0] cfblk180_out1;  // uint8
  wire [7:0] cfblk36_const_val_1;  // uint8
  wire [7:0] cfblk36_out1;  // uint8


  assign cfblk181_out1_is_not0 = In2 != 8'b00000000;



  assign cfblk182_out1_is_not0 = In1 != 8'b00000000;



  assign cfblk5_out1 = cfblk181_out1_is_not0 & cfblk182_out1_is_not0;



  assign cfblk180_out1 = {7'b0, cfblk5_out1};



  assign cfblk36_const_val_1 = 8'b00000000;



  assign cfblk36_out1 = cfblk180_out1 + cfblk36_const_val_1;



  assign Out1 = cfblk36_out1;

endmodule  // Mysubsystem_28

