// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1552\sampleModel1552_2_sub\Mysubsystem_13.v
// Created: 2024-08-12 18:28:00
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_13
// Source Path: sampleModel1552_2_sub/Subsystem/Mysubsystem_13
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_13
          (In1,
           In2,
           Out1);


  input   [7:0] In1;  // uint8
  input   [7:0] In2;  // uint8
  output  [7:0] Out1;  // uint8


  wire [7:0] cfblk145_out1;  // uint8


  assign cfblk145_out1 = In1 + In2;



  assign Out1 = cfblk145_out1;

endmodule  // Mysubsystem_13

