// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel2027\sampleModel2027_3_sub\Mysubsystem_29.v
// Created: 2024-07-03 01:17:46
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_29
// Source Path: sampleModel2027_3_sub/Subsystem/Mysubsystem_29
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_29
          (In1,
           In2,
           Out1);


  input   In1;
  input   [7:0] In2;  // uint8
  output  signed [7:0] Out1;  // int8


  wire [7:0] cfblk142_out1;  // ufix8_En7
  reg [7:0] cfblk63_out1;  // ufix8_E7
  wire signed [7:0] cfblk21_out1;  // int8
  reg [7:0] cfblk63_div_temp;  // ufix8_E7


  assign cfblk142_out1 = {In1, 7'b0000000};



  always @(In2, cfblk142_out1) begin
    cfblk63_div_temp = 8'b00000000;
    if (cfblk142_out1 == 8'b00000000) begin
      cfblk63_out1 = 8'b11111111;
    end
    else begin
      cfblk63_div_temp = In2 / cfblk142_out1;
      cfblk63_out1 = cfblk63_div_temp;
    end
  end



  assign cfblk21_out1 = (cfblk63_out1 > 8'b00000000 ? 8'sb00000001 :
              8'sb00000000);



  assign Out1 = cfblk21_out1;

endmodule  // Mysubsystem_29

