// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1879\sampleModel1879_1_sub\Mysubsystem_28.v
// Created: 2024-08-15 01:52:58
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_28
// Source Path: sampleModel1879_1_sub/Subsystem/Mysubsystem_28
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_28
          (clk,
           reset,
           enb,
           In1,
           In2,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] In1;  // uint8
  input   [7:0] In2;  // uint8
  output  [15:0] Out1;  // uint16


  wire [15:0] cfblk160_out1;  // uint16
  wire [7:0] cfblk200_out1;  // uint8
  wire [15:0] cfblk32_out1;  // uint16
  reg [15:0] cfblk115_out1;  // uint16
  reg [15:0] cfblk115_div_temp;  // ufix16


  cfblk160 u_cfblk160 (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .y(cfblk160_out1)  // uint16
                       );

  assign cfblk200_out1 = cfblk160_out1[7:0];



  DotProduct u_cfblk32_inst (.in1(In1),  // uint8
                             .in2(cfblk200_out1),  // uint8
                             .out1(cfblk32_out1)  // uint16
                             );

  always @(In2, cfblk32_out1) begin
    cfblk115_div_temp = 16'b0000000000000000;
    if (cfblk32_out1 == 16'b0000000000000000) begin
      cfblk115_out1 = 16'b1111111111111111;
    end
    else begin
      cfblk115_div_temp = In2 / cfblk32_out1;
      cfblk115_out1 = cfblk115_div_temp;
    end
  end



  assign Out1 = cfblk115_out1;

endmodule  // Mysubsystem_28

