vlib work
vlog  cfblk1.v
vlog  Mysubsystem_2.v
vlog  cfblk130.v
vlog  cfblk131.v
vlog  cfblk132.v
vlog  cfblk133.v
vlog  cfblk134.v
vlog  cfblk4.v
vlog  DotProduct.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  DotProduct_block3.v
vlog  DotProduct_block4.v
vlog  DotProduct_block5.v
vlog  DotProduct_block6.v
vlog  DotProduct_block7.v
vlog  DotProduct_block8.v
vlog  Subsystem.v
vlog  Subsystem_tb.v
