// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1972\sampleModel1972_1_sub\Mysubsystem_28.v
// Created: 2024-08-16 04:45:32
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_28
// Source Path: sampleModel1972_1_sub/Subsystem/Mysubsystem_28
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_28
          (clk,
           reset,
           enb,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  output  [31:0] Out1;  // ufix32_En15


  wire [15:0] cfblk133_out1;  // uint16
  wire [31:0] cfblk59_out1;  // ufix32_En15


  cfblk133 u_cfblk133 (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .y(cfblk133_out1)  // uint16
                       );

  assign cfblk59_out1 = {1'b0, {cfblk133_out1, 15'b000000000000000}};



  assign Out1 = cfblk59_out1;

endmodule  // Mysubsystem_28

