cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1775_1_sub/Subsystem/Mysubsystem_24','user1');
hilite_system('sampleModel1775_1_sub/Subsystem/Mysubsystem_24/cfblk12','user1');
hilite_system('sampleModel1775_1_sub/Subsystem/Mysubsystem_24/cfblk59','user1');
hilite_system('sampleModel1775_1_sub/Subsystem/Mysubsystem_31','user1');
hilite_system('sampleModel1775_1_sub/Subsystem/Mysubsystem_31/cfblk94','user1');
hilite_system('sampleModel1775_1_sub/Subsystem/cfblk4','user1');
hilite_system('sampleModel1775_1_sub/Subsystem/cfblk55','user1');
hilite_system('sampleModel1775_1_sub/Subsystem/cfblk81','user1');
