// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1775\sampleModel1775_1_sub\Mysubsystem_29.v
// Created: 2024-08-14 06:18:57
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_29
// Source Path: sampleModel1775_1_sub/Subsystem/Mysubsystem_29
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_29
          (In1,
           Out1);


  input   In1;
  output  [7:0] Out1;  // uint8


  wire [7:0] cfblk187_out1;  // uint8


  assign cfblk187_out1 = {7'b0, In1};



  assign Out1 = cfblk187_out1;

endmodule  // Mysubsystem_29

