cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk10','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk104','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk107','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk111','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk121','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk124','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk126','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk137','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk137/Force to be scalar','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk137/Increment Real World','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk137/Output','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk137/Wrap To Zero','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk146','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk150','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk152','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk160','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk18','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk30','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk42','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk47','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk7','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk95','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk97','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk137/Increment Real World/FixPt Constant','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk137/Increment Real World/FixPt Data Type Duplicate','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk137/Increment Real World/FixPt Sum1','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk137/Wrap To Zero/Constant','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk137/Wrap To Zero/FixPt Data Type Duplicate1','user1');
hilite_system('sampleModel1899_1_sub_sub/Subsystem/Subsystem/cfblk137/Wrap To Zero/FixPt Switch','user1');
