cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/Mysubsystem_28/cfblk147','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/Mysubsystem_28/cfblk153','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/Mysubsystem_3','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/Mysubsystem_3/cfblk2','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/Mysubsystem_3/cfblk2/Negative','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/Mysubsystem_34','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/Mysubsystem_34/cfblk123','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/Mysubsystem_34/cfblk123/Increment Real World','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/Mysubsystem_34/cfblk123/Wrap To Zero','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/cfblk112','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/cfblk126','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/cfblk127','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/cfblk128','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/cfblk138','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/cfblk22','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/cfblk3','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/cfblk3/Positive','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/cfblk45','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/cfblk5','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/cfblk58','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/cfblk65','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/cfblk7','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/cfblk7/Nonpositive','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/Mysubsystem_34/cfblk123/Increment Real World/FixPt Data Type Duplicate','user1');
hilite_system('sampleModel1598_5_sub_sub/Subsystem/Subsystem/Mysubsystem_34/cfblk123/Wrap To Zero/FixPt Data Type Duplicate1','user1');
