cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1616_4_sub/Subsystem/cfblk142','user1');
hilite_system('sampleModel1616_4_sub/Subsystem/cfblk147','user1');
hilite_system('sampleModel1616_4_sub/Subsystem/cfblk5','user1');
hilite_system('sampleModel1616_4_sub/Subsystem/cfblk73','user1');
hilite_system('sampleModel1616_4_sub/Subsystem/cfblk75','user1');
hilite_system('sampleModel1616_4_sub/Subsystem/cfblk95','user1');
