cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1449_sub/Subsystem/cfblk1','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk1/Positive','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk11','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk125','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk136','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk136/Force to be scalar','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk136/Increment Real World','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk136/Output','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk136/Wrap To Zero','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk152','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk48','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk61','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk62','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk67','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk70','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk89','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk92','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk136/Increment Real World/FixPt Constant','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk136/Increment Real World/FixPt Data Type Duplicate','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk136/Increment Real World/FixPt Sum1','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk136/Wrap To Zero/Constant','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk136/Wrap To Zero/FixPt Data Type Duplicate1','user1');
hilite_system('sampleModel1449_sub/Subsystem/cfblk136/Wrap To Zero/FixPt Switch','user1');
