// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1503\sampleModel1503_2_sub\Mysubsystem_34.v
// Created: 2024-06-10 05:18:51
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_34
// Source Path: sampleModel1503_2_sub/Subsystem/Mysubsystem_34
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_34
          (clk,
           reset,
           enb,
           In1,
           y);


  input   clk;
  input   reset;
  input   enb;
  input   [15:0] In1;  // ufix16_En7
  output  y;


  reg [15:0] cfblk177_reg [0:1];  // ufix16 [2]
  wire [15:0] cfblk177_reg_next [0:1];  // ufix16_En7 [2]
  wire [15:0] cfblk177_out1;  // ufix16_En7
  wire cfblk1_out1;


  always @(posedge clk or posedge reset)
    begin : cfblk177_process
      if (reset == 1'b1) begin
        cfblk177_reg[0] <= 16'b0000000000000000;
        cfblk177_reg[1] <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          cfblk177_reg[0] <= cfblk177_reg_next[0];
          cfblk177_reg[1] <= cfblk177_reg_next[1];
        end
      end
    end

  assign cfblk177_out1 = cfblk177_reg[1];
  assign cfblk177_reg_next[0] = In1;
  assign cfblk177_reg_next[1] = cfblk177_reg[0];



  cfblk1 u_cfblk1 (.u(cfblk177_out1),  // ufix16_En7
                   .y(cfblk1_out1)
                   );

  assign y = cfblk1_out1;

endmodule  // Mysubsystem_34

