cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/Mysubsystem_45','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/Mysubsystem_45/cfblk101','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/Mysubsystem_45/cfblk137','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/Mysubsystem_45/cfblk17','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/Mysubsystem_45/cfblk22','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk1','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk10','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk10/Delay Input1','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk10/FixPt Relational Operator','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk10/Positive','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk100','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk102','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk103','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk104','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk105','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk106','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk107','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk108','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk109','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk11','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk110','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk111','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk112','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk113','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk114','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk115','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk116','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk117','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk118','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk119','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk12','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk120','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk121','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk122','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk123','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk124','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk125','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk126','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk127','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk128','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk129','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk13','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk130','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk131','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk132','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk133','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk134','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk135','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk136','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk138','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk139','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk14','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk140','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk141','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk142','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk143','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk144','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk145','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk146','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk147','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk148','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk149','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk15','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk150','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk151','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk152','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk154','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk155','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk155/Force to be scalar','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk155/Increment Real World','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk155/Output','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk155/Wrap To Zero','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk156','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk157','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk158','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk159','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk16','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk160','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk161','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk162','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk163','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk164','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk165','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk166','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk167','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk168','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk169','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk170','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk171','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk172','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk173','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk174','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk175','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk176','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk177','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk178','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk179','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk18','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk180','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk181','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk182','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk183','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk184','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk185','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk186','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk187','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk188','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk189','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk19','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk190','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk191','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk192','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk193','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk194','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk195','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk196','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk197','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk198','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk199','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk2','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk20','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk200','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk201','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk202','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk203','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk204','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk205','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk206','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk207','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk208','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk209','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk21','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk210','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk211','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk212','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk213','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk214','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk215','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk216','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk217','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk218','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk219','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk220','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk221','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk222','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk223','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk23','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk24','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk25','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk26','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk27','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk28','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk29','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk3','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk3/Delay Input1','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk3/FixPt Relational Operator','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk30','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk31','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk32','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk33','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk34','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk35','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk36','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk37','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk38','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk39','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk4','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk4/Delay Input1','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk4/FixPt Relational Operator','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk40','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk41','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk42','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk43','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk44','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk45','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk46','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk47','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk48','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk49','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk5','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk5/Delay Input1','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk5/FixPt Relational Operator','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk5/Negative','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk50','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk51','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk52','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk53','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk54','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk55','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk56','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk57','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk58','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk59','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk6','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk6/Delay Input1','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk6/FixPt Relational Operator','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk60','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk61','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk62','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk63','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk64','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk65','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk66','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk67','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk68','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk69','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk7','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk7/Delay Input1','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk7/FixPt Relational Operator','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk70','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk71','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk72','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk73','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk74','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk75','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk76','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk77','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk78','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk79','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk8','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk80','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk81','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk82','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk83','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk84','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk85','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk86','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk87','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk88','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk89','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk9','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk90','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk91','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk92','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk93','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk94','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk95','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk96','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk97','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk98','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk99','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk10/Positive/Compare','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk10/Positive/Constant','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk155/Increment Real World/FixPt Constant','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk155/Increment Real World/FixPt Data Type Duplicate','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk155/Increment Real World/FixPt Sum1','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk155/Wrap To Zero/Constant','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk155/Wrap To Zero/FixPt Data Type Duplicate1','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk155/Wrap To Zero/FixPt Switch','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk5/Negative/Compare','user1');
hilite_system('sampleModel1955_2_sub_sub_sub/Subsystem/Subsystem/Subsystem/cfblk5/Negative/Constant','user1');
