cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/Mysubsystem_4','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/Mysubsystem_4/cfblk142','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/Mysubsystem_43','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/Mysubsystem_43/cfblk6','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/Mysubsystem_43/cfblk6/Delay Input1','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/Mysubsystem_43/cfblk6/FixPt Relational Operator','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/Mysubsystem_43/cfblk6/Nonnegative','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/Mysubsystem_43/cfblk63','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/cfblk103','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/cfblk116','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/cfblk124','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/cfblk143','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/cfblk195','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/cfblk196','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/cfblk35','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/cfblk4','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/cfblk44','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/cfblk69','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/cfblk76','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/cfblk88','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/cfblk91','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/Mysubsystem_43/cfblk6/Nonnegative/Compare','user1');
hilite_system('sampleModel1432_2_sub_sub/Subsystem/Subsystem/Mysubsystem_43/cfblk6/Nonnegative/Constant','user1');
