cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1879_1_sub_sub/Subsystem/Subsystem/Mysubsystem_26','user1');
hilite_system('sampleModel1879_1_sub_sub/Subsystem/Subsystem/Mysubsystem_26/cfblk164','user1');
hilite_system('sampleModel1879_1_sub_sub/Subsystem/Subsystem/Mysubsystem_37','user1');
hilite_system('sampleModel1879_1_sub_sub/Subsystem/Subsystem/Mysubsystem_37/cfblk152','user1');
hilite_system('sampleModel1879_1_sub_sub/Subsystem/Subsystem/cfblk105','user1');
hilite_system('sampleModel1879_1_sub_sub/Subsystem/Subsystem/cfblk119','user1');
hilite_system('sampleModel1879_1_sub_sub/Subsystem/Subsystem/cfblk24','user1');
hilite_system('sampleModel1879_1_sub_sub/Subsystem/Subsystem/cfblk47','user1');
hilite_system('sampleModel1879_1_sub_sub/Subsystem/Subsystem/cfblk60','user1');
hilite_system('sampleModel1879_1_sub_sub/Subsystem/Subsystem/cfblk76','user1');
hilite_system('sampleModel1879_1_sub_sub/Subsystem/Subsystem/cfblk89','user1');
