vlib work
vlog  Mysubsystem_2.v
vlog  Mysubsystem_26.v
vlog  Mysubsystem_33.v
vlog  Mysubsystem_9.v
vlog  cfblk132.v
vlog  DotProduct.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  DotProduct_block3.v
vlog  DotProduct_block4.v
vlog  Subsystem.v
