vlib work
vlog  Mysubsystem_16.v
vlog  Mysubsystem_49.v
vlog  DotProduct.v
vlog  Mysubsystem_7.v
vlog  cfblk145.v
vlog  cfblk146.v
vlog  cfblk147.v
vlog  cfblk3.v
vlog  cfblk4.v
vlog  cfblk5.v
vlog  cfblk6.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  DotProduct_block3.v
vlog  DotProduct_block4.v
vlog  DotProduct_block5.v
vlog  DotProduct_block6.v
vlog  Subsystem.v
vlog  Subsystem_tb.v
