// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1507\sampleModel1507_1_sub\Mysubsystem_12.v
// Created: 2024-06-10 05:31:22
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_12
// Source Path: sampleModel1507_1_sub/Subsystem/Mysubsystem_12
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_12
          (Out1);


  output  [7:0] Out1;  // uint8


  wire [7:0] cfblk140_out1;  // uint8


  assign cfblk140_out1 = 8'b00000000;



  assign Out1 = cfblk140_out1;

endmodule  // Mysubsystem_12

