cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1659_sub/Subsystem/cfblk122','user1');
hilite_system('sampleModel1659_sub/Subsystem/cfblk150','user1');
hilite_system('sampleModel1659_sub/Subsystem/cfblk150/Increment Real World','user1');
hilite_system('sampleModel1659_sub/Subsystem/cfblk150/Wrap To Zero','user1');
hilite_system('sampleModel1659_sub/Subsystem/cfblk70','user1');
hilite_system('sampleModel1659_sub/Subsystem/cfblk78','user1');
