// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1965\sampleModel1965_4_sub_sub\Mysubsystem_22.v
// Created: 2024-08-16 03:33:20
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_22
// Source Path: sampleModel1965_4_sub_sub/Subsystem/Subsystem/Mysubsystem_22
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_22
          (In1,
           In2,
           Out1);


  input   [7:0] In1;  // uint8
  input   [7:0] In2;  // uint8
  output  [7:0] Out1;  // uint8


  wire [7:0] cfblk122_out1;  // uint8
  wire [7:0] cfblk159_out1;  // uint8


  assign cfblk122_out1 = In1 - In2;



  cfblk159 u_cfblk159 (.In1(cfblk122_out1),  // uint8
                       .Out1(cfblk159_out1)  // uint8
                       );

  assign Out1 = cfblk159_out1;

endmodule  // Mysubsystem_22

