// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1668\sampleModel1668_4_sub\Mysubsystem_10.v
// Created: 2024-08-13 11:57:30
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_10
// Source Path: sampleModel1668_4_sub/Subsystem/Mysubsystem_10
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_10
          (clk,
           reset,
           enb,
           In1,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] In1;  // uint8
  output  [15:0] Out1;  // uint16


  wire [15:0] cfblk134_out1;  // uint16
  reg [15:0] cfblk67_out1;  // uint16
  reg [16:0] cfblk67_div_temp;  // ufix17
  reg [16:0] cfblk67_t_0_0;  // ufix17


  cfblk134 u_cfblk134 (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .y(cfblk134_out1)  // uint16
                       );

  always @(In1, cfblk134_out1) begin
    cfblk67_div_temp = 17'b00000000000000000;
    cfblk67_t_0_0 = 17'b00000000000000000;
    if (In1 == 8'b00000000) begin
      cfblk67_out1 = 16'b1111111111111111;
    end
    else begin
      cfblk67_t_0_0 = {1'b0, cfblk134_out1};
      cfblk67_div_temp = cfblk67_t_0_0 / In1;
      if (cfblk67_div_temp[16] != 1'b0) begin
        cfblk67_out1 = 16'b1111111111111111;
      end
      else begin
        cfblk67_out1 = cfblk67_div_temp[15:0];
      end
    end
  end



  assign Out1 = cfblk67_out1;

endmodule  // Mysubsystem_10

