vlib work
vlog  Mysubsystem_11.v
vlog  cfblk1.v
vlog  Mysubsystem_21.v
vlog  DotProduct.v
vlog  Mysubsystem_22.v
vlog  Mysubsystem_23.v
vlog  Mysubsystem_30.v
vlog  Mysubsystem_36.v
vlog  cfblk130.v
vlog  cfblk131.v
vlog  cfblk132.v
vlog  cfblk133.v
vlog  Positive.v
vlog  cfblk3.v
vlog  Nonpositive.v
vlog  cfblk7.v
vlog  Nonpositive_block.v
vlog  cfblk9.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  DotProduct_block3.v
vlog  DotProduct_block4.v
vlog  DotProduct_block5.v
vlog  DotProduct_block6.v
vlog  DotProduct_block7.v
vlog  DotProduct_block8.v
vlog  DotProduct_block9.v
vlog  DotProduct_block10.v
vlog  DotProduct_block11.v
vlog  DotProduct_block12.v
vlog  Subsystem.v
vlog  Subsystem_tb.v
