cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel2003_sub_sub/Subsystem/Subsystem/cfblk105','user1');
hilite_system('sampleModel2003_sub_sub/Subsystem/Subsystem/cfblk112','user1');
hilite_system('sampleModel2003_sub_sub/Subsystem/Subsystem/cfblk163','user1');
hilite_system('sampleModel2003_sub_sub/Subsystem/Subsystem/cfblk182','user1');
hilite_system('sampleModel2003_sub_sub/Subsystem/Subsystem/cfblk185','user1');
hilite_system('sampleModel2003_sub_sub/Subsystem/Subsystem/cfblk30','user1');
hilite_system('sampleModel2003_sub_sub/Subsystem/Subsystem/cfblk53','user1');
hilite_system('sampleModel2003_sub_sub/Subsystem/Subsystem/cfblk77','user1');
hilite_system('sampleModel2003_sub_sub/Subsystem/Subsystem/cfblk87','user1');
hilite_system('sampleModel2003_sub_sub/Subsystem/Subsystem/cfblk91','user1');
