// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1468\sampleModel1468_5_sub\Mysubsystem_6.v
// Created: 2024-06-10 04:08:31
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_6
// Source Path: sampleModel1468_5_sub/Subsystem/Mysubsystem_6
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_6
          (clk,
           reset,
           enb,
           U,
           Out1,
           Out2);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] U;  // uint8
  output  [7:0] Out1;  // uint8
  output  [7:0] Out2;  // uint8


  wire cfblk1_out1;
  wire [7:0] cfblk171_out1;  // uint8


  cfblk1 u_cfblk1 (.clk(clk),
                   .reset(reset),
                   .enb(enb),
                   .U(U),  // uint8
                   .Y(cfblk1_out1)
                   );

  assign cfblk171_out1 = {7'b0, cfblk1_out1};



  assign Out1 = cfblk171_out1;

  assign Out2 = cfblk171_out1;

endmodule  // Mysubsystem_6

