// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1866\sampleModel1866_3_sub_sub\Mysubsystem_35.v
// Created: 2024-08-14 22:40:02
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_35
// Source Path: sampleModel1866_3_sub_sub/Subsystem/Subsystem/Mysubsystem_35
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_35
          (Out1);


  output  [7:0] Out1;  // uint8


  wire [7:0] cfblk158_out1;  // uint8


  assign cfblk158_out1 = 8'b00000000;



  assign Out1 = cfblk158_out1;

endmodule  // Mysubsystem_35

