cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1897_sub/Subsystem/cfblk1','user1');
hilite_system('sampleModel1897_sub/Subsystem/cfblk110','user1');
hilite_system('sampleModel1897_sub/Subsystem/cfblk152','user1');
hilite_system('sampleModel1897_sub/Subsystem/cfblk153','user1');
hilite_system('sampleModel1897_sub/Subsystem/cfblk20','user1');
hilite_system('sampleModel1897_sub/Subsystem/cfblk69','user1');
hilite_system('sampleModel1897_sub/Subsystem/cfblk88','user1');
hilite_system('sampleModel1897_sub/Subsystem/cfblk92','user1');
