// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1668\sampleModel1668_2_sub\Mysubsystem_36.v
// Created: 2024-08-13 11:45:57
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_36
// Source Path: sampleModel1668_2_sub/Subsystem/Mysubsystem_36
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_36
          (clk,
           reset,
           enb,
           In1,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] In1;  // uint8
  output  [7:0] Out1;  // uint8


  reg [7:0] cfblk163_reg [0:1];  // ufix8 [2]
  wire [7:0] cfblk163_reg_next [0:1];  // ufix8 [2]
  wire [7:0] cfblk163_out1;  // uint8
  wire cfblk170_out1;
  wire cfblk1_out1;
  wire [7:0] cfblk171_out1;  // uint8
  wire [7:0] cfblk130_const_val_1;  // uint8
  wire [7:0] cfblk130_out1;  // uint8
  wire [7:0] dtc_out;  // ufix8
  wire [7:0] cfblk118_out1;  // uint8


  always @(posedge clk or posedge reset)
    begin : cfblk163_process
      if (reset == 1'b1) begin
        cfblk163_reg[0] <= 8'b00000000;
        cfblk163_reg[1] <= 8'b00000000;
      end
      else begin
        if (enb) begin
          cfblk163_reg[0] <= cfblk163_reg_next[0];
          cfblk163_reg[1] <= cfblk163_reg_next[1];
        end
      end
    end

  assign cfblk163_out1 = cfblk163_reg[1];
  assign cfblk163_reg_next[0] = In1;
  assign cfblk163_reg_next[1] = cfblk163_reg[0];



  assign cfblk170_out1 = (cfblk163_out1 != 8'b00000000 ? 1'b1 :
              1'b0);



  assign cfblk1_out1 = 1'b1;



  assign cfblk171_out1 = {7'b0, cfblk1_out1};



  assign cfblk130_const_val_1 = 8'b00000000;



  assign cfblk130_out1 = cfblk171_out1 + cfblk130_const_val_1;



  assign dtc_out = cfblk130_out1;



  assign cfblk118_out1 = dtc_out;



  assign Out1 = cfblk118_out1;

endmodule  // Mysubsystem_36

