cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1406_2_sub/Subsystem/Mysubsystem_43','user1');
hilite_system('sampleModel1406_2_sub/Subsystem/Mysubsystem_43/cfblk100','user1');
hilite_system('sampleModel1406_2_sub/Subsystem/Mysubsystem_43/cfblk51','user1');
hilite_system('sampleModel1406_2_sub/Subsystem/Mysubsystem_44','user1');
hilite_system('sampleModel1406_2_sub/Subsystem/Mysubsystem_44/cfblk7','user1');
hilite_system('sampleModel1406_2_sub/Subsystem/cfblk74','user1');
hilite_system('sampleModel1406_2_sub/Subsystem/cfblk81','user1');
