cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1400_sub/Subsystem/cfblk155','user1');
hilite_system('sampleModel1400_sub/Subsystem/cfblk185','user1');
hilite_system('sampleModel1400_sub/Subsystem/cfblk186','user1');
hilite_system('sampleModel1400_sub/Subsystem/cfblk56','user1');
hilite_system('sampleModel1400_sub/Subsystem/cfblk63','user1');
hilite_system('sampleModel1400_sub/Subsystem/cfblk89','user1');
hilite_system('sampleModel1400_sub/Subsystem/cfblk97','user1');
