vlib work
vlog  DotProduct.v
vlog  Mysubsystem_19.v
vlog  Mysubsystem_37.v
vlog  cfblk1.v
vlog  cfblk133.v
vlog  cfblk134.v
vlog  cfblk3.v
vlog  cfblk5.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  DotProduct_block3.v
vlog  DotProduct_block4.v
vlog  DotProduct_block5.v
vlog  DotProduct_block6.v
vlog  DotProduct_block7.v
vlog  Subsystem.v
vlog  Subsystem_tb.v
