vlib work
vlog  Increment_Real_World.v
vlog  Wrap_To_Zero.v
vlog  cfblk138.v
vlog  Increment_Real_World_block.v
vlog  Wrap_To_Zero_block.v
vlog  cfblk140.v
vlog  Increment_Real_World_block1.v
vlog  Wrap_To_Zero_block1.v
vlog  cfblk141.v
vlog  cfblk142.v
vlog  cfblk143.v
vlog  cfblk144.v
vlog  cfblk2.v
vlog  Positive.v
vlog  cfblk3.v
vlog  cfblk6.v
vlog  Nonpositive.v
vlog  cfblk7.v
vlog  cfblk8.v
vlog  DotProduct.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  DotProduct_block3.v
vlog  DotProduct_block4.v
vlog  DotProduct_block5.v
vlog  Subsystem.v
