// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1880\sampleModel1880_3_sub\Mysubsystem_21.v
// Created: 2024-06-10 16:08:27
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_21
// Source Path: sampleModel1880_3_sub/Subsystem/Mysubsystem_21
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_21
          (In1,
           Out1);


  input   [7:0] In1;  // uint8
  output  [7:0] Out1;  // uint8


  wire [7:0] cfblk104_out1;  // uint8


  assign cfblk104_out1 = (In1 > 8'b00000000 ? 8'b00000001 :
              8'b00000000);



  assign Out1 = cfblk104_out1;

endmodule  // Mysubsystem_21

