cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1931_sub/Subsystem/cfblk108','user1');
hilite_system('sampleModel1931_sub/Subsystem/cfblk109','user1');
hilite_system('sampleModel1931_sub/Subsystem/cfblk130','user1');
hilite_system('sampleModel1931_sub/Subsystem/cfblk132','user1');
hilite_system('sampleModel1931_sub/Subsystem/cfblk24','user1');
hilite_system('sampleModel1931_sub/Subsystem/cfblk44','user1');
hilite_system('sampleModel1931_sub/Subsystem/cfblk72','user1');
