vlib work
vlog  cfblk1.v
vlog  Increment_Real_World.v
vlog  Wrap_To_Zero.v
vlog  cfblk143.v
vlog  cfblk147.v
vlog  cfblk148.v
vlog  cfblk2.v
vlog  cfblk3.v
vlog  cfblk4.v
vlog  DotProduct.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  DotProduct_block3.v
vlog  DotProduct_block4.v
vlog  DotProduct_block5.v
vlog  Subsystem.v
vlog  Subsystem_tb.v
