// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1475\sampleModel1475_5_sub\Mysubsystem_8.v
// Created: 2024-07-01 02:01:12
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_8
// Source Path: sampleModel1475_5_sub/Subsystem/Mysubsystem_8
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_8
          (In1,
           In2,
           Out1);


  input   [7:0] In1;  // uint8
  input   [7:0] In2;  // uint8
  output  [7:0] Out1;  // uint8


  wire [7:0] cfblk72_const_val_1;  // uint8
  wire [7:0] cfblk72_out1;  // uint8
  wire [7:0] cfblk39_out1;  // uint8
  wire [7:0] dtc_out;  // ufix8
  wire [7:0] cfblk78_out1;  // uint8


  assign cfblk72_const_val_1 = 8'b00000000;



  assign cfblk72_out1 = In2 + cfblk72_const_val_1;



  assign cfblk39_out1 = In1 + cfblk72_out1;



  assign dtc_out = cfblk39_out1;



  assign cfblk78_out1 = dtc_out;



  assign Out1 = cfblk78_out1;

endmodule  // Mysubsystem_8

