// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1475\sampleModel1475_5_sub\Mysubsystem_16.v
// Created: 2024-06-10 04:26:30
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_16
// Source Path: sampleModel1475_5_sub/Subsystem/Mysubsystem_16
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_16
          (In1,
           In2,
           In3,
           Out1);


  input   [7:0] In1;  // uint8
  input   [7:0] In2;  // uint8
  input   [7:0] In3;  // uint8
  output  [15:0] Out1;  // uint16


  wire [7:0] cfblk7_out1;  // uint8
  wire [15:0] cfblk77_out1;  // uint16


  assign cfblk7_out1 = In1 + In3;



  DotProduct u_cfblk77_inst (.in1(cfblk7_out1),  // uint8
                             .in2(In2),  // uint8
                             .out1(cfblk77_out1)  // uint16
                             );

  assign Out1 = cfblk77_out1;

endmodule  // Mysubsystem_16

