cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1811_3_sub/Subsystem/Mysubsystem_30','user1');
hilite_system('sampleModel1811_3_sub/Subsystem/Mysubsystem_30/cfblk46','user1');
hilite_system('sampleModel1811_3_sub/Subsystem/Mysubsystem_30/cfblk47','user1');
hilite_system('sampleModel1811_3_sub/Subsystem/Mysubsystem_32','user1');
hilite_system('sampleModel1811_3_sub/Subsystem/Mysubsystem_32/cfblk129','user1');
hilite_system('sampleModel1811_3_sub/Subsystem/Mysubsystem_32/cfblk129/Increment Real World','user1');
hilite_system('sampleModel1811_3_sub/Subsystem/Mysubsystem_32/cfblk129/Wrap To Zero','user1');
