cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1503_5_sub/Subsystem/Mysubsystem_4','user1');
hilite_system('sampleModel1503_5_sub/Subsystem/Mysubsystem_4/cfblk152','user1');
hilite_system('sampleModel1503_5_sub/Subsystem/Mysubsystem_4/cfblk86','user1');
hilite_system('sampleModel1503_5_sub/Subsystem/Mysubsystem_4/cfblk95','user1');
hilite_system('sampleModel1503_5_sub/Subsystem/cfblk31','user1');
hilite_system('sampleModel1503_5_sub/Subsystem/cfblk97','user1');
