cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1426_sub_sub/Subsystem/Subsystem/cfblk10','user1');
hilite_system('sampleModel1426_sub_sub/Subsystem/Subsystem/cfblk101','user1');
hilite_system('sampleModel1426_sub_sub/Subsystem/Subsystem/cfblk103','user1');
hilite_system('sampleModel1426_sub_sub/Subsystem/Subsystem/cfblk112','user1');
hilite_system('sampleModel1426_sub_sub/Subsystem/Subsystem/cfblk114','user1');
hilite_system('sampleModel1426_sub_sub/Subsystem/Subsystem/cfblk116','user1');
hilite_system('sampleModel1426_sub_sub/Subsystem/Subsystem/cfblk120','user1');
hilite_system('sampleModel1426_sub_sub/Subsystem/Subsystem/cfblk130','user1');
hilite_system('sampleModel1426_sub_sub/Subsystem/Subsystem/cfblk131','user1');
hilite_system('sampleModel1426_sub_sub/Subsystem/Subsystem/cfblk26','user1');
hilite_system('sampleModel1426_sub_sub/Subsystem/Subsystem/cfblk30','user1');
hilite_system('sampleModel1426_sub_sub/Subsystem/Subsystem/cfblk32','user1');
hilite_system('sampleModel1426_sub_sub/Subsystem/Subsystem/cfblk35','user1');
hilite_system('sampleModel1426_sub_sub/Subsystem/Subsystem/cfblk50','user1');
hilite_system('sampleModel1426_sub_sub/Subsystem/Subsystem/cfblk79','user1');
