// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel2081\sampleModel2081_4_sub\Mysubsystem_31.v
// Created: 2024-08-17 04:44:13
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_31
// Source Path: sampleModel2081_4_sub/Subsystem/Mysubsystem_31
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_31
          (u,
           Out1);


  input   [7:0] u;  // uint8
  output  [7:0] Out1;  // ufix8_En7


  wire cfblk1_out1;
  wire [7:0] cfblk29_out1;  // ufix8_En7


  cfblk1 u_cfblk1 (.u(u),  // uint8
                   .y(cfblk1_out1)
                   );

  assign cfblk29_out1 = {cfblk1_out1, 7'b0000000};



  assign Out1 = cfblk29_out1;

endmodule  // Mysubsystem_31

