vlib work
vlog  cfblk1.v
vlog  Mysubsystem_31.v
vlog  Mysubsystem_32.v
vlog  Mysubsystem_33.v
vlog  Mysubsystem_34.v
vlog  DotProduct.v
vlog  Mysubsystem_6.v
vlog  cfblk133.v
vlog  cfblk134.v
vlog  cfblk3.v
vlog  cfblk5.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  DotProduct_block3.v
vlog  DotProduct_block4.v
vlog  DotProduct_block5.v
vlog  DotProduct_block6.v
vlog  DotProduct_block7.v
vlog  Subsystem.v
vlog  Subsystem_tb.v
