cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1810_sub/Subsystem/cfblk104','user1');
hilite_system('sampleModel1810_sub/Subsystem/cfblk109','user1');
hilite_system('sampleModel1810_sub/Subsystem/cfblk134','user1');
hilite_system('sampleModel1810_sub/Subsystem/cfblk134/Increment Real World','user1');
hilite_system('sampleModel1810_sub/Subsystem/cfblk134/Wrap To Zero','user1');
hilite_system('sampleModel1810_sub/Subsystem/cfblk40','user1');
hilite_system('sampleModel1810_sub/Subsystem/cfblk76','user1');
