vlib work
vlog  Mysubsystem_15.v
vlog  DotProduct.v
vlog  Mysubsystem_21.v
vlog  Mysubsystem_3.v
vlog  Nonnegative.v
vlog  cfblk1.v
vlog  Mysubsystem_43.v
vlog  cfblk140.v
vlog  cfblk6.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  DotProduct_block3.v
vlog  DotProduct_block4.v
vlog  DotProduct_block5.v
vlog  DotProduct_block6.v
vlog  DotProduct_block7.v
vlog  DotProduct_block8.v
vlog  DotProduct_block9.v
vlog  DotProduct_block10.v
vlog  Subsystem.v
vlog  Subsystem_tb.v
