cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1871_4_sub/Subsystem/Mysubsystem_2','user1');
hilite_system('sampleModel1871_4_sub/Subsystem/Mysubsystem_2/cfblk101','user1');
hilite_system('sampleModel1871_4_sub/Subsystem/Mysubsystem_2/cfblk130','user1');
hilite_system('sampleModel1871_4_sub/Subsystem/Mysubsystem_2/cfblk137','user1');
hilite_system('sampleModel1871_4_sub/Subsystem/Mysubsystem_2/cfblk17','user1');
hilite_system('sampleModel1871_4_sub/Subsystem/Mysubsystem_2/cfblk34','user1');
hilite_system('sampleModel1871_4_sub/Subsystem/Mysubsystem_2/cfblk44','user1');
