cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1406_4_sub/Subsystem/Mysubsystem_37','user1');
hilite_system('sampleModel1406_4_sub/Subsystem/Mysubsystem_37/cfblk100','user1');
hilite_system('sampleModel1406_4_sub/Subsystem/Mysubsystem_37/cfblk51','user1');
hilite_system('sampleModel1406_4_sub/Subsystem/Mysubsystem_37/cfblk7','user1');
hilite_system('sampleModel1406_4_sub/Subsystem/cfblk74','user1');
hilite_system('sampleModel1406_4_sub/Subsystem/cfblk81','user1');
