cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1695_5_sub_sub/Subsystem/Subsystem/Mysubsystem_10/cfblk85','user1');
hilite_system('sampleModel1695_5_sub_sub/Subsystem/Subsystem/cfblk104','user1');
hilite_system('sampleModel1695_5_sub_sub/Subsystem/Subsystem/cfblk111','user1');
hilite_system('sampleModel1695_5_sub_sub/Subsystem/Subsystem/cfblk119','user1');
hilite_system('sampleModel1695_5_sub_sub/Subsystem/Subsystem/cfblk146','user1');
hilite_system('sampleModel1695_5_sub_sub/Subsystem/Subsystem/cfblk20','user1');
hilite_system('sampleModel1695_5_sub_sub/Subsystem/Subsystem/cfblk39','user1');
hilite_system('sampleModel1695_5_sub_sub/Subsystem/Subsystem/cfblk42','user1');
hilite_system('sampleModel1695_5_sub_sub/Subsystem/Subsystem/cfblk44','user1');
hilite_system('sampleModel1695_5_sub_sub/Subsystem/Subsystem/cfblk5','user1');
hilite_system('sampleModel1695_5_sub_sub/Subsystem/Subsystem/cfblk54','user1');
hilite_system('sampleModel1695_5_sub_sub/Subsystem/Subsystem/cfblk58','user1');
hilite_system('sampleModel1695_5_sub_sub/Subsystem/Subsystem/cfblk79','user1');
hilite_system('sampleModel1695_5_sub_sub/Subsystem/Subsystem/cfblk8','user1');
hilite_system('sampleModel1695_5_sub_sub/Subsystem/Subsystem/cfblk92','user1');
hilite_system('sampleModel1695_5_sub_sub/Subsystem/Subsystem/cfblk93','user1');
