// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1659\sampleModel1659_5_sub\Mysubsystem_47.v
// Created: 2024-06-10 09:52:11
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_47
// Source Path: sampleModel1659_5_sub/Subsystem/Mysubsystem_47
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_47
          (clk,
           reset,
           enb,
           y);


  input   clk;
  input   reset;
  input   enb;
  output  [15:0] y;  // uint16


  wire [15:0] cfblk148_out1;  // uint16


  cfblk148 u_cfblk148 (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .y(cfblk148_out1)  // uint16
                       );

  assign y = cfblk148_out1;

endmodule  // Mysubsystem_47

