cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1785_sub/Subsystem/cfblk104','user1');
hilite_system('sampleModel1785_sub/Subsystem/cfblk121','user1');
hilite_system('sampleModel1785_sub/Subsystem/cfblk121/Force to be scalar','user1');
hilite_system('sampleModel1785_sub/Subsystem/cfblk121/Increment Real World','user1');
hilite_system('sampleModel1785_sub/Subsystem/cfblk121/Output','user1');
hilite_system('sampleModel1785_sub/Subsystem/cfblk121/Wrap To Zero','user1');
hilite_system('sampleModel1785_sub/Subsystem/cfblk122','user1');
hilite_system('sampleModel1785_sub/Subsystem/cfblk122/Increment Real World','user1');
hilite_system('sampleModel1785_sub/Subsystem/cfblk122/Wrap To Zero','user1');
hilite_system('sampleModel1785_sub/Subsystem/cfblk121/Increment Real World/FixPt Constant','user1');
hilite_system('sampleModel1785_sub/Subsystem/cfblk121/Increment Real World/FixPt Data Type Duplicate','user1');
hilite_system('sampleModel1785_sub/Subsystem/cfblk121/Increment Real World/FixPt Sum1','user1');
hilite_system('sampleModel1785_sub/Subsystem/cfblk121/Wrap To Zero/Constant','user1');
hilite_system('sampleModel1785_sub/Subsystem/cfblk121/Wrap To Zero/FixPt Data Type Duplicate1','user1');
hilite_system('sampleModel1785_sub/Subsystem/cfblk121/Wrap To Zero/FixPt Switch','user1');
