vlib work
vlog  Increment_Real_World_block.v
vlog  Wrap_To_Zero_block.v
vlog  cfblk123.v
vlog  cfblk126.v
vlog  cfblk127.v
vlog  cfblk128.v
vlog  DotProduct.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  DotProduct_block3.v
vlog  Subsystem.v
