cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1775_2_sub/Subsystem/Mysubsystem_26','user1');
hilite_system('sampleModel1775_2_sub/Subsystem/Mysubsystem_26/cfblk12','user1');
hilite_system('sampleModel1775_2_sub/Subsystem/cfblk4','user1');
hilite_system('sampleModel1775_2_sub/Subsystem/cfblk55','user1');
hilite_system('sampleModel1775_2_sub/Subsystem/cfblk59','user1');
hilite_system('sampleModel1775_2_sub/Subsystem/cfblk81','user1');
hilite_system('sampleModel1775_2_sub/Subsystem/cfblk94','user1');
