vlib work
vlog  Mysubsystem_29.v
vlog  Mysubsystem_38.v
vlog  cfblk148.v
vlog  cfblk149.v
vlog  cfblk3.v
vlog  DotProduct.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  DotProduct_block3.v
vlog  DotProduct_block4.v
vlog  DotProduct_block5.v
vlog  DotProduct_block6.v
vlog  Subsystem.v
vlog  Subsystem_tb.v
