cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1443_sub/Subsystem/cfblk105','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk107','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk117','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk124','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk128','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk128/Force to be scalar','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk128/Increment Real World','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk128/Output','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk128/Wrap To Zero','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk147','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk148','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk2','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk2/Delay Input1','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk2/FixPt Relational Operator','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk2/Nonpositive','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk20','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk21','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk22','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk25','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk34','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk47','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk48','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk49','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk5','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk51','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk53','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk62','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk77','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk83','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk84','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk87','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk90','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk128/Increment Real World/FixPt Constant','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk128/Increment Real World/FixPt Data Type Duplicate','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk128/Increment Real World/FixPt Sum1','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk128/Wrap To Zero/Constant','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk128/Wrap To Zero/FixPt Data Type Duplicate1','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk128/Wrap To Zero/FixPt Switch','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk2/Nonpositive/Compare','user1');
hilite_system('sampleModel1443_sub/Subsystem/cfblk2/Nonpositive/Constant','user1');
