// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1666\sampleModel1666_3_sub\Mysubsystem_29.v
// Created: 2024-07-01 14:20:40
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_29
// Source Path: sampleModel1666_3_sub/Subsystem/Mysubsystem_29
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_29
          (clk,
           reset,
           enb,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  output  [15:0] Out1;  // uint16


  wire [15:0] cfblk138_out1;  // uint16


  cfblk138 u_cfblk138 (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .y(cfblk138_out1)  // uint16
                       );

  assign Out1 = cfblk138_out1;

endmodule  // Mysubsystem_29

