// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1695\sampleModel1695_4_sub\Mysubsystem_26.v
// Created: 2024-08-13 17:17:40
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_26
// Source Path: sampleModel1695_4_sub/Subsystem/Mysubsystem_26
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_26
          (In1,
           In2,
           Out1);


  input   [7:0] In1;  // uint8
  input   In2;
  output  [15:0] Out1;  // uint16


  wire [7:0] cfblk167_out1;  // uint8
  wire [15:0] cfblk11_out1;  // uint16


  assign cfblk167_out1 = {7'b0, In2};



  DotProduct u_cfblk11_inst (.in1(In1),  // uint8
                             .in2(cfblk167_out1),  // uint8
                             .out1(cfblk11_out1)  // uint16
                             );

  assign Out1 = cfblk11_out1;

endmodule  // Mysubsystem_26

