// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1695\sampleModel1695_4_sub\Mysubsystem_37.v
// Created: 2024-08-13 17:17:40
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_37
// Source Path: sampleModel1695_4_sub/Subsystem/Mysubsystem_37
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_37
          (In1,
           In2,
           Out1);


  input   [7:0] In1;  // uint8
  input   [15:0] In2;  // uint16
  output  [15:0] Out1;  // uint16


  wire signed [31:0] cfblk109_sub_temp;  // sfix32
  wire signed [31:0] cfblk109_1;  // sfix32
  wire signed [31:0] cfblk109_2;  // sfix32
  wire [15:0] cfblk109_out1;  // uint16


  assign cfblk109_1 = {16'b0, In2};
  assign cfblk109_2 = {24'b0, In1};
  assign cfblk109_sub_temp = cfblk109_1 - cfblk109_2;
  assign cfblk109_out1 = cfblk109_sub_temp[15:0];



  assign Out1 = cfblk109_out1;

endmodule  // Mysubsystem_37

