vlib work
vlog  Mysubsystem_1.v
vlog  Mysubsystem_22.v
vlog  DotProduct.v
vlog  Mysubsystem_25.v
vlog  Mysubsystem_31.v
vlog  cfblk130.v
vlog  cfblk2.v
vlog  Nonnegative.v
vlog  cfblk4.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  Subsystem.v
