cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1581_sub/Subsystem/cfblk103','user1');
hilite_system('sampleModel1581_sub/Subsystem/cfblk104','user1');
hilite_system('sampleModel1581_sub/Subsystem/cfblk110','user1');
hilite_system('sampleModel1581_sub/Subsystem/cfblk121','user1');
hilite_system('sampleModel1581_sub/Subsystem/cfblk30','user1');
hilite_system('sampleModel1581_sub/Subsystem/cfblk42','user1');
hilite_system('sampleModel1581_sub/Subsystem/cfblk97','user1');
