cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1871_1_sub/Subsystem/Mysubsystem_4/cfblk17','user1');
hilite_system('sampleModel1871_1_sub/Subsystem/Mysubsystem_5/cfblk34','user1');
hilite_system('sampleModel1871_1_sub/Subsystem/Mysubsystem_5/cfblk44','user1');
hilite_system('sampleModel1871_1_sub/Subsystem/Mysubsystem_6','user1');
hilite_system('sampleModel1871_1_sub/Subsystem/Mysubsystem_6/cfblk101','user1');
hilite_system('sampleModel1871_1_sub/Subsystem/Mysubsystem_6/cfblk130','user1');
hilite_system('sampleModel1871_1_sub/Subsystem/Mysubsystem_6/cfblk137','user1');
