vlib work
vlog  Mysubsystem_30.v
vlog  Mysubsystem_4.v
vlog  Mysubsystem_5.v
vlog  cfblk132.v
vlog  DotProduct.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  DotProduct_block3.v
vlog  DotProduct_block4.v
vlog  Subsystem.v
