cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1944_1_sub_sub/Subsystem/Subsystem/Mysubsystem_2','user1');
hilite_system('sampleModel1944_1_sub_sub/Subsystem/Subsystem/Mysubsystem_2/cfblk114','user1');
hilite_system('sampleModel1944_1_sub_sub/Subsystem/Subsystem/Mysubsystem_2/cfblk50','user1');
hilite_system('sampleModel1944_1_sub_sub/Subsystem/Subsystem/Mysubsystem_49','user1');
hilite_system('sampleModel1944_1_sub_sub/Subsystem/Subsystem/Mysubsystem_49/cfblk31','user1');
hilite_system('sampleModel1944_1_sub_sub/Subsystem/Subsystem/cfblk20','user1');
hilite_system('sampleModel1944_1_sub_sub/Subsystem/Subsystem/cfblk24','user1');
hilite_system('sampleModel1944_1_sub_sub/Subsystem/Subsystem/cfblk26','user1');
hilite_system('sampleModel1944_1_sub_sub/Subsystem/Subsystem/cfblk56','user1');
hilite_system('sampleModel1944_1_sub_sub/Subsystem/Subsystem/cfblk58','user1');
hilite_system('sampleModel1944_1_sub_sub/Subsystem/Subsystem/cfblk59','user1');
hilite_system('sampleModel1944_1_sub_sub/Subsystem/Subsystem/cfblk65','user1');
hilite_system('sampleModel1944_1_sub_sub/Subsystem/Subsystem/cfblk72','user1');
hilite_system('sampleModel1944_1_sub_sub/Subsystem/Subsystem/cfblk8','user1');
hilite_system('sampleModel1944_1_sub_sub/Subsystem/Subsystem/cfblk92','user1');
