// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1598\sampleModel1598_5_sub\Mysubsystem_28.v
// Created: 2024-07-01 10:08:03
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_28
// Source Path: sampleModel1598_5_sub/Subsystem/Mysubsystem_28
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_28
          (cfblk120);


  output  [7:0] cfblk120;  // uint8


  wire [7:0] cfblk1_out1;  // uint8


  assign cfblk1_out1 = 8'b00000000;



  assign cfblk120 = cfblk1_out1;

endmodule  // Mysubsystem_28

