cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1762_sub/Subsystem/cfblk135','user1');
hilite_system('sampleModel1762_sub/Subsystem/cfblk150','user1');
hilite_system('sampleModel1762_sub/Subsystem/cfblk44','user1');
hilite_system('sampleModel1762_sub/Subsystem/cfblk52','user1');
hilite_system('sampleModel1762_sub/Subsystem/cfblk70','user1');
hilite_system('sampleModel1762_sub/Subsystem/cfblk73','user1');
