cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1811_2_sub_sub/Subsystem/Subsystem/Mysubsystem_20','user1');
hilite_system('sampleModel1811_2_sub_sub/Subsystem/Subsystem/Mysubsystem_20/cfblk47','user1');
hilite_system('sampleModel1811_2_sub_sub/Subsystem/Subsystem/Mysubsystem_29','user1');
hilite_system('sampleModel1811_2_sub_sub/Subsystem/Subsystem/Mysubsystem_29/cfblk129','user1');
hilite_system('sampleModel1811_2_sub_sub/Subsystem/Subsystem/Mysubsystem_29/cfblk129/Increment Real World','user1');
hilite_system('sampleModel1811_2_sub_sub/Subsystem/Subsystem/Mysubsystem_29/cfblk129/Wrap To Zero','user1');
hilite_system('sampleModel1811_2_sub_sub/Subsystem/Subsystem/Mysubsystem_29/cfblk46','user1');
