cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1552_sub/Subsystem/cfblk119','user1');
hilite_system('sampleModel1552_sub/Subsystem/cfblk14','user1');
hilite_system('sampleModel1552_sub/Subsystem/cfblk2','user1');
hilite_system('sampleModel1552_sub/Subsystem/cfblk42','user1');
hilite_system('sampleModel1552_sub/Subsystem/cfblk87','user1');
hilite_system('sampleModel1552_sub/Subsystem/cfblk93','user1');
hilite_system('sampleModel1552_sub/Subsystem/cfblk97','user1');
