vlib work
vlog  Mysubsystem_13.v
vlog  Mysubsystem_6.v
vlog  DotProduct.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  DotProduct_block3.v
vlog  DotProduct_block4.v
vlog  Subsystem.v
