cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sampleModel1869_3_sub_sub/Subsystem/Subsystem/Mysubsystem_33','user1');
hilite_system('sampleModel1869_3_sub_sub/Subsystem/Subsystem/Mysubsystem_33/cfblk138','user1');
hilite_system('sampleModel1869_3_sub_sub/Subsystem/Subsystem/Mysubsystem_33/cfblk165','user1');
hilite_system('sampleModel1869_3_sub_sub/Subsystem/Subsystem/Mysubsystem_33/cfblk36','user1');
hilite_system('sampleModel1869_3_sub_sub/Subsystem/Subsystem/Mysubsystem_34','user1');
hilite_system('sampleModel1869_3_sub_sub/Subsystem/Subsystem/Mysubsystem_34/cfblk150','user1');
hilite_system('sampleModel1869_3_sub_sub/Subsystem/Subsystem/Mysubsystem_34/cfblk150/Force to be scalar','user1');
hilite_system('sampleModel1869_3_sub_sub/Subsystem/Subsystem/Mysubsystem_34/cfblk150/Increment Real World','user1');
hilite_system('sampleModel1869_3_sub_sub/Subsystem/Subsystem/Mysubsystem_34/cfblk150/Output','user1');
hilite_system('sampleModel1869_3_sub_sub/Subsystem/Subsystem/Mysubsystem_34/cfblk150/Wrap To Zero','user1');
hilite_system('sampleModel1869_3_sub_sub/Subsystem/Subsystem/Mysubsystem_34/cfblk150/Increment Real World/FixPt Constant','user1');
hilite_system('sampleModel1869_3_sub_sub/Subsystem/Subsystem/Mysubsystem_34/cfblk150/Increment Real World/FixPt Data Type Duplicate','user1');
hilite_system('sampleModel1869_3_sub_sub/Subsystem/Subsystem/Mysubsystem_34/cfblk150/Increment Real World/FixPt Sum1','user1');
hilite_system('sampleModel1869_3_sub_sub/Subsystem/Subsystem/Mysubsystem_34/cfblk150/Wrap To Zero/Constant','user1');
hilite_system('sampleModel1869_3_sub_sub/Subsystem/Subsystem/Mysubsystem_34/cfblk150/Wrap To Zero/FixPt Data Type Duplicate1','user1');
hilite_system('sampleModel1869_3_sub_sub/Subsystem/Subsystem/Mysubsystem_34/cfblk150/Wrap To Zero/FixPt Switch','user1');
