// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1933\sampleModel1933_4_sub\Mysubsystem_7.v
// Created: 2024-06-10 17:57:41
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_7
// Source Path: sampleModel1933_4_sub/Subsystem/Mysubsystem_7
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_7
          (In1,
           In2,
           Out1);


  input   [7:0] In1;  // uint8
  input   [15:0] In2;  // ufix16_En7
  output  [7:0] Out1;  // uint8


  wire [15:0] cfblk78_out1;  // ufix16_En7
  wire [7:0] cfblk177_out1;  // uint8
  wire [7:0] cfblk178_out1;  // uint8
  wire [15:0] cfblk33_out1;  // uint16
  wire [7:0] cfblk176_out1;  // uint8


  assign cfblk78_out1 = {1'b0, {In1, 7'b0000000}};



  assign cfblk177_out1 = cfblk78_out1[14:7];



  assign cfblk178_out1 = In2[14:7];



  DotProduct u_cfblk33_inst (.in1(cfblk177_out1),  // uint8
                             .in2(cfblk178_out1),  // uint8
                             .out1(cfblk33_out1)  // uint16
                             );

  assign cfblk176_out1 = cfblk33_out1[7:0];



  assign Out1 = cfblk176_out1;

endmodule  // Mysubsystem_7

