// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1667\sampleModel1667_4_sub\Mysubsystem_10.v
// Created: 2024-06-10 10:03:35
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_10
// Source Path: sampleModel1667_4_sub/Subsystem/Mysubsystem_10
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_10
          (In1,
           Out1);


  input   [7:0] In1;  // uint8
  output  signed [15:0] Out1;  // int16


  wire [15:0] cfblk82_out1;  // ufix16_En7
  wire signed [15:0] cfblk19_out1;  // int16


  assign cfblk82_out1 = {1'b0, {In1, 7'b0000000}};



  assign cfblk19_out1 = (cfblk82_out1 > 16'b0000000000000000 ? 16'sb0000000000000001 :
              16'sb0000000000000000);



  assign Out1 = cfblk19_out1;

endmodule  // Mysubsystem_10

