// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1655\sampleModel1655_5_sub\Mysubsystem_29.v
// Created: 2024-07-01 13:54:52
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_29
// Source Path: sampleModel1655_5_sub/Subsystem/Mysubsystem_29
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_29
          (clk,
           reset,
           enb,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  output  [15:0] Out1;  // ufix16_En7


  wire [7:0] cfblk146_out1;  // uint8
  wire [15:0] cfblk106_out1;  // ufix16_En7


  cfblk146 u_cfblk146 (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .y(cfblk146_out1)  // uint8
                       );

  assign cfblk106_out1 = {1'b0, {cfblk146_out1, 7'b0000000}};



  assign Out1 = cfblk106_out1;

endmodule  // Mysubsystem_29

