vlib work
vlog  Mysubsystem_24.v
vlog  Mysubsystem_30.v
vlog  cfblk1.v
vlog  cfblk129.v
vlog  DotProduct.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  Subsystem.v
