// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1931\sampleModel1931_5_sub\Mysubsystem_11.v
// Created: 2024-08-15 16:22:16
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_11
// Source Path: sampleModel1931_5_sub/Subsystem/Mysubsystem_11
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_11
          (In1,
           In2,
           cfblk138);


  input   [7:0] In1;  // uint8
  input   [7:0] In2;  // uint8
  output  [7:0] cfblk138;  // uint8


  wire [7:0] cfblk16_out1;  // uint8
  wire [7:0] cfblk70_out1;  // uint8


  assign cfblk16_out1 = (In2 > 8'b00000000 ? 8'b00000001 :
              8'b00000000);



  assign cfblk70_out1 = cfblk16_out1 + In1;



  assign cfblk138 = cfblk70_out1;

endmodule  // Mysubsystem_11

