vlib work
vlog  cfblk1.v
vlog  Mysubsystem_27.v
vlog  Mysubsystem_37.v
vlog  cfblk129.v
vlog  DotProduct.v
vlog  DotProduct_block.v
vlog  DotProduct_block1.v
vlog  DotProduct_block2.v
vlog  Subsystem.v
vlog  Subsystem_tb.v
