// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1561\sampleModel1561_5_sub\Mysubsystem_34.v
// Created: 2024-07-01 06:56:52
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_34
// Source Path: sampleModel1561_5_sub/Subsystem/Mysubsystem_34
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_34
          (u,
           Out1);


  input   [7:0] u;  // uint8
  output  signed [1:0] Out1;  // sfix2


  wire cfblk2_out1;  // ufix1
  wire cfblk118_out1;  // ufix1
  wire signed [1:0] cfblk72_out1;  // sfix2


  assign cfblk2_out1 = (&u[7:0]);



  assign cfblk118_out1 = cfblk2_out1;



  assign cfblk72_out1 = (cfblk118_out1 > 1'b0 ? 2'sb01 :
              2'sb00);



  assign Out1 = cfblk72_out1;

endmodule  // Mysubsystem_34

