// -------------------------------------------------------------
// 
// File Name: D:\ljx\code\GUIDANCE-ljx3\slsf_randgen\slsf\reportsneo\2024-06-06-16-53-16\Verilog_hdlsrc\sampleModel1652\sampleModel1652_2_sub\Mysubsystem_44.v
// Created: 2024-07-01 13:31:06
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mysubsystem_44
// Source Path: sampleModel1652_2_sub/Subsystem/Mysubsystem_44
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mysubsystem_44
          (y);


  output  [7:0] y;  // uint8


  wire [7:0] cfblk145_out1;  // uint8


  assign cfblk145_out1 = 8'b00000000;



  assign y = cfblk145_out1;

endmodule  // Mysubsystem_44

